### Functions

In [22]:
def sign(x):
    if x>0:
        return 'positive'
    elif x<0:
        return 'negative'
    else:
        return 'zero'

In [24]:
for x in [-1,0,1]:
    print (sign(x))

negative
zero
positive


In [28]:
def hello(name, loud=False):
    if loud:
        print('Hello, %s!' % name.upper()) 
    else:
        print ('Hello, %s' % name)

In [29]:
hello('Bob')

Hello, Bob


In [30]:
hello('Fred', loud=True)

Hello, FRED!


### Classes

In [35]:
class Greeter(object):
    
    #Constructor
    def __init__(self, name):
        self.name = name 
        
    # Instance Method
    def greet(self, loud=False):
        if loud:
            print('Hello, %s!' % self.name.upper()) 
        else:
            print ('Hello, %s' % self.name)

In [36]:
g = Greeter('Fred')
g.greet()
g.greet(loud=True)

Hello, Fred
Hello, FRED!


https://docs.python.org/2/tutorial/classes.html

### Numpy

In [1]:
import numpy as np
# import package as [명칭]
# from package import [package class]

In [19]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [20]:
b = np.array([[1,2,3],[4,5,6]])

In [21]:
print (b[0,0], b[0,1], b[1,0])

1 2 4


In [10]:
import pandas as pd

In [12]:
pd.DataFrame(b)

0  1  2
0  1  2  3
1  4  5  6

In [15]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2), 7)
c

C:\Users\Home2014\Anaconda3\lib\site-packages\numpy\core\numeric.py:294: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 7.,  7.],
       [ 7.,  7.]])

In [16]:
d = np.eye(2) #2X2 identity matrix , 항등행렬, 단위행렬
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [39]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
b = a[:2, 1:3]

In [42]:
print (a[0,1])

2


In [46]:
b[0,0] = 77

In [50]:
print (a[0,1])

77


In [52]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [53]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

In [54]:
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [55]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 7.,  6.,  2.,  1.],
       [ 1.,  8.,  1.,  5.],
       [ 4.,  1.,  9.,  8.]])

In [56]:
a.shape

(3, 4)

In [57]:
a.ravel()

array([ 7.,  6.,  2.,  1.,  1.,  8.,  1.,  5.,  4.,  1.,  9.,  8.])

In [58]:
a.shape= (6,2)

In [60]:
a.T

array([[ 7.,  2.,  1.,  1.,  4.,  9.],
       [ 6.,  1.,  8.,  5.,  1.,  8.]])

In [63]:
a.resize((2,6))
a

array([[ 7.,  6.,  2.,  1.,  1.,  8.],
       [ 1.,  5.,  4.,  1.,  9.,  8.]])

In [64]:
a.reshape(3,-1)

array([[ 7.,  6.,  2.,  1.],
       [ 1.,  8.,  1.,  5.],
       [ 4.,  1.,  9.,  8.]])

In [75]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 0.,  7.],
       [ 3.,  0.]])

In [76]:
b = np.floor(10*np.random.random((2,2)))

In [77]:
np.vstack((a,b))

array([[ 0.,  7.],
       [ 3.,  0.],
       [ 7.,  5.],
       [ 9.,  6.]])

In [78]:
np.hstack((a,b))

array([[ 0.,  7.,  7.,  5.],
       [ 3.,  0.,  9.,  6.]])

In [79]:
np.column_stack((a,b))

array([[ 0.,  7.,  7.,  5.],
       [ 3.,  0.,  9.,  6.]])

In [81]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 6.,  0.,  1.,  5.,  5.,  0.,  6.,  4.,  8.,  6.,  8.,  4.],
       [ 2.,  7.,  4.,  5.,  0.,  3.,  5.,  4.,  0.,  1.,  3.,  1.]])

In [82]:
np.hsplit(a,3)

[array([[ 6.,  0.,  1.,  5.],
        [ 2.,  7.,  4.,  5.]]), array([[ 5.,  0.,  6.,  4.],
        [ 0.,  3.,  5.,  4.]]), array([[ 8.,  6.,  8.,  4.],
        [ 0.,  1.,  3.,  1.]])]

In [83]:
np.hsplit(a,(3,4))

[array([[ 6.,  0.,  1.],
        [ 2.,  7.,  4.]]), array([[ 5.],
        [ 5.]]), array([[ 5.,  0.,  6.,  4.,  8.,  6.,  8.,  4.],
        [ 0.,  3.,  5.,  4.,  0.,  1.,  3.,  1.]])]

### Numpy가 자주 사용되는 분야는 선형대수학 (Linear Algebra)
### 선형대수학은 행렬을 바탕으로 한 분야로써 Python은 Java나 C보다 Split 및 데이터를 핸들링하는데 있어 중요한 역할을 합니다

### Pandas

In [84]:
s = pd.Series([1,3,5,np.nan,6,8])

In [85]:
s

0     1
1     3
2     5
3   NaN
4     6
5     8
dtype: float64

In [86]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [87]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.867170 -0.184638  0.054984 -0.405436
2013-01-02  0.823686 -1.029531 -0.649686 -0.970633
2013-01-03  0.100822 -2.360175 -0.289948 -3.110635
2013-01-04 -0.383273  0.257298 -1.138826  1.119709
2013-01-05  1.746356 -0.771503 -0.478934 -0.144298
2013-01-06  0.688458  0.794751  0.154920  0.783064

In [89]:
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })

In [90]:
df2

A          B  C  D      E    F
0  1 2013-01-02  1  3   test  foo
1  1 2013-01-02  1  3  train  foo
2  1 2013-01-02  1  3   test  foo
3  1 2013-01-02  1  3  train  foo

In [91]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [92]:
df.head()

A         B         C         D
2013-01-01  0.867170 -0.184638  0.054984 -0.405436
2013-01-02  0.823686 -1.029531 -0.649686 -0.970633
2013-01-03  0.100822 -2.360175 -0.289948 -3.110635
2013-01-04 -0.383273  0.257298 -1.138826  1.119709
2013-01-05  1.746356 -0.771503 -0.478934 -0.144298

In [94]:
df.tail(3)

A         B         C         D
2013-01-04 -0.383273  0.257298 -1.138826  1.119709
2013-01-05  1.746356 -0.771503 -0.478934 -0.144298
2013-01-06  0.688458  0.794751  0.154920  0.783064

In [95]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [96]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [97]:
df.values

array([[ 0.86716996, -0.18463752,  0.05498372, -0.40543637],
       [ 0.82368607, -1.02953086, -0.64968629, -0.97063331],
       [ 0.10082225, -2.36017491, -0.28994798, -3.11063486],
       [-0.38327289,  0.25729795, -1.13882595,  1.11970876],
       [ 1.74635593, -0.77150267, -0.47893406, -0.14429783],
       [ 0.68845758,  0.79475091,  0.15492047,  0.78306354]])

In [98]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.640536 -0.548966 -0.391248 -0.454705
std    0.727945  1.108992  0.477710  1.511938
min   -0.383273 -2.360175 -1.138826 -3.110635
25%    0.247731 -0.965024 -0.606998 -0.829334
50%    0.756072 -0.478070 -0.384441 -0.274867
75%    0.856299  0.146814 -0.031249  0.551223
max    1.746356  0.794751  0.154920  1.119709

In [99]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.867170    0.823686    0.100822   -0.383273    1.746356    0.688458
B   -0.184638   -1.029531   -2.360175    0.257298   -0.771503    0.794751
C    0.054984   -0.649686   -0.289948   -1.138826   -0.478934    0.154920
D   -0.405436   -0.970633   -3.110635    1.119709   -0.144298    0.783064

In [103]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -0.405436  0.054984 -0.184638  0.867170
2013-01-02 -0.970633 -0.649686 -1.029531  0.823686
2013-01-03 -3.110635 -0.289948 -2.360175  0.100822
2013-01-04  1.119709 -1.138826  0.257298 -0.383273
2013-01-05 -0.144298 -0.478934 -0.771503  1.746356
2013-01-06  0.783064  0.154920  0.794751  0.688458

In [102]:
df.sort_values(by='B')

A         B         C         D
2013-01-03  0.100822 -2.360175 -0.289948 -3.110635
2013-01-02  0.823686 -1.029531 -0.649686 -0.970633
2013-01-05  1.746356 -0.771503 -0.478934 -0.144298
2013-01-01  0.867170 -0.184638  0.054984 -0.405436
2013-01-04 -0.383273  0.257298 -1.138826  1.119709
2013-01-06  0.688458  0.794751  0.154920  0.783064

In [105]:
df['A']

2013-01-01    0.867170
2013-01-02    0.823686
2013-01-03    0.100822
2013-01-04   -0.383273
2013-01-05    1.746356
2013-01-06    0.688458
Freq: D, Name: A, dtype: float64

In [106]:
df.loc[dates[0]]

A    0.867170
B   -0.184638
C    0.054984
D   -0.405436
Name: 2013-01-01 00:00:00, dtype: float64

In [107]:
df.loc[:,['A','B']]

A         B
2013-01-01  0.867170 -0.184638
2013-01-02  0.823686 -1.029531
2013-01-03  0.100822 -2.360175
2013-01-04 -0.383273  0.257298
2013-01-05  1.746356 -0.771503
2013-01-06  0.688458  0.794751

In [108]:
df.loc['20130102':'20130104',['A','B']]

A         B
2013-01-02  0.823686 -1.029531
2013-01-03  0.100822 -2.360175
2013-01-04 -0.383273  0.257298

In [109]:
df.loc['20130102',['A','B']]

A    0.823686
B   -1.029531
Name: 2013-01-02 00:00:00, dtype: float64

In [110]:
df.loc[dates[0],'A']

0.86716996333588126

In [111]:
df.at[dates[0],'A']

0.86716996333588126

In [112]:
df.iloc[3]

A   -0.383273
B    0.257298
C   -1.138826
D    1.119709
Name: 2013-01-04 00:00:00, dtype: float64

In [113]:
df.iloc[3:5,0:2]

A         B
2013-01-04 -0.383273  0.257298
2013-01-05  1.746356 -0.771503

In [114]:
df.iloc[[1,2,4],[0,2]]

A         C
2013-01-02  0.823686 -0.649686
2013-01-03  0.100822 -0.289948
2013-01-05  1.746356 -0.478934

In [115]:
df.iloc[1:3,:]

A         B         C         D
2013-01-02  0.823686 -1.029531 -0.649686 -0.970633
2013-01-03  0.100822 -2.360175 -0.289948 -3.110635

In [116]:
df.iloc[:,1:3]

B         C
2013-01-01 -0.184638  0.054984
2013-01-02 -1.029531 -0.649686
2013-01-03 -2.360175 -0.289948
2013-01-04  0.257298 -1.138826
2013-01-05 -0.771503 -0.478934
2013-01-06  0.794751  0.154920

In [117]:
df.iloc[1,1]

-1.0295308596768642

In [118]:
df.iat[1,1]

-1.0295308596768642

In [119]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102', periods=6))

In [120]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [121]:
df['F'] = s1

In [122]:
df.at[dates[0],'A'] = 0

In [123]:
df.iat[0,1] = 0

In [124]:
df.loc[:,'D'] = np.array([5] * len(df))

In [125]:
df

A         B         C  D   F
2013-01-01  0.000000  0.000000  0.054984  5 NaN
2013-01-02  0.823686 -1.029531 -0.649686  5   1
2013-01-03  0.100822 -2.360175 -0.289948  5   2
2013-01-04 -0.383273  0.257298 -1.138826  5   3
2013-01-05  1.746356 -0.771503 -0.478934  5   4
2013-01-06  0.688458  0.794751  0.154920  5   5

In [126]:
df2 = df.copy()

In [127]:
df2[df2 > 0] = -df2

In [128]:
df2

A         B         C  D   F
2013-01-01  0.000000  0.000000 -0.054984 -5 NaN
2013-01-02 -0.823686 -1.029531 -0.649686 -5  -1
2013-01-03 -0.100822 -2.360175 -0.289948 -5  -2
2013-01-04 -0.383273 -0.257298 -1.138826 -5  -3
2013-01-05 -1.746356 -0.771503 -0.478934 -5  -4
2013-01-06 -0.688458 -0.794751 -0.154920 -5  -5

In [129]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])

In [130]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [131]:
df1

A         B         C  D   F   E
2013-01-01  0.000000  0.000000  0.054984  5 NaN   1
2013-01-02  0.823686 -1.029531 -0.649686  5   1   1
2013-01-03  0.100822 -2.360175 -0.289948  5   2 NaN
2013-01-04 -0.383273  0.257298 -1.138826  5   3 NaN

In [132]:
df1.dropna(how='any')

A         B         C  D  F  E
2013-01-02  0.823686 -1.029531 -0.649686  5  1  1

In [133]:
df1.fillna(value=5)

A         B         C  D  F  E
2013-01-01  0.000000  0.000000  0.054984  5  5  1
2013-01-02  0.823686 -1.029531 -0.649686  5  1  1
2013-01-03  0.100822 -2.360175 -0.289948  5  2  5
2013-01-04 -0.383273  0.257298 -1.138826  5  3  5

In [134]:
pd.isnull(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [135]:
df.apply(np.cumsum)

A         B         C   D   F
2013-01-01  0.000000  0.000000  0.054984   5 NaN
2013-01-02  0.823686 -1.029531 -0.594703  10   1
2013-01-03  0.924508 -3.389706 -0.884651  15   3
2013-01-04  0.541235 -3.132408 -2.023476  20   6
2013-01-05  2.287591 -3.903910 -2.502411  25  10
2013-01-06  2.976049 -3.109160 -2.347490  30  15

In [136]:
df.apply(lambda x: x.max() - x.min())

A    2.129629
B    3.154926
C    1.293746
D    0.000000
F    4.000000
dtype: float64

In [137]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [138]:
s

0    5
1    4
2    5
3    4
4    5
5    3
6    1
7    4
8    2
9    4
dtype: int32

In [139]:
s.value_counts()

4    4
5    3
3    1
2    1
1    1
dtype: int64